name: Java CI com Maven

on:
  push:
    branches: ["main"]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - 'LICENSE'
      - 'CONTRIBUTING.md'
  pull_request:
    branches: ["main"]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - 'LICENSE'
      - 'CONTRIBUTING.md'

jobs:
  build:
    name: Build (CI)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build e Testes com Maven
        run: mvn clean test

      - name: Upload do Artefato
        uses: actions/upload-artifact@v4
        with:
          name: projeto-ci-inicial
          path: target/*.jar
